### ISSUE TITLE
Portability

### ISSUE THREAD

**Issue by agentofuser** [mogenslund/liq2#1]
Hi Mogens, glad to see liquid staying active :)

Are you planning on making it usable on browsers / ClojureScript? I don't know much about the differences, so I don't know how hard that would be, just curious about where you see liq2 going. Thank you!

**Comment by mogenslund** [comment]
Hi Helder

In the beginning, my intent was to make everything work and java and through Lumo simultaneously, to insure some sort of portability. Since I have been very focussed on the model part, I have ditched Lumo support, just for a while. My intent is to take it up again, as soon as the model is more in place. My hope is that java support + Lumo support will make it easy do other ports, since I am forced to think in portability. Concretely, my idea is to separate out the parts that differ to a limited area. This should limit the parts, that needs to be considered for further ports. (I also have in mind to see, what can be done in the direction of Babashka.) Besides IO differences, I might encounter some limitations regarding evaluation. In-editor evaluation is one of my favorites features, but maybe we can live without in a Browser, depending on the usecase. I am getting close to getting the model some kind of right and consistent. When I am happy I will start working on cleaning op, model for extensions and portability.

Best regards,
Mogens

**Comment by agentofuser** [comment]
Good to know that portability is somewhere in the roadmap, there is no rush. While iterating on the model and dogfooding you're right to keep it as easy as possible for yourself to make changes. Thank you for replying :)
